export const CATEGORIES = [
  { key: 'all', label: 'Все' },
  { key: 'front', label: 'Передняя оптика' },
  { key: 'rear', label: 'Задние фонари' },
  { key: 'fog', label: 'Противотуманные фары' },
];

export const PRODUCTS = [
  {
    id: 1,
    title: 'Передняя оптика BMW X5 E70 (Рест)',
    price: '80.000₽',
    priceValue: 80000,
    category: 'front',
    image: '',
    description: 'Описание для передней оптики BMW X5 E70 (Рест).',
    features: {
      'Светодиоды': '12 штук',
      'Цвет': 'Кристально прозрачный',
      'Вольтаж': '12V',
      'Гарантия': '2 года',
    },
  },
  {
    id: 2,
    title: 'Противотуманные фары Subaru Forester',
    price: '8500₽',
    priceValue: 8500,
    category: 'fog',
    image: '',
    description: 'Описание для противотуманных фар Subaru Forester.',
    features: {
      'Светодиоды': '12 штук',
      'Цвет': 'Кристально прозрачный',
      'Вольтаж': '12V',
      'Гарантия': '2 года',
    },
  },
  {
    id: 3,
    title: 'Задний фонарь Subaru Impreza WRX/STI/XV Crosstrek LED',
    price: '6900₽',
    priceValue: 6900,
    category: 'rear',
    image: '',
    description: 'Для Subaru Impreza и XV Crosstrek, поскольку отверстие для заднего фонаря на бампере не было открыто полностью, вы не сможете использовать металлический кронштейн, поставляемый в комплекте, вместо этого вам придется изготовить несколько прокладок, чтобы равномерно расположить этот светодиодный задний противотуманный фонарь в отверстии для заднего противотуманного фонаря.',
    features: {
      'Светодиоды': '12 штук',
      'Цвет': 'Кристально прозрачный',
      'Вольтаж': '12V',
      'Гарантия': '2 года',
    },
  },
  { id: 4, title: 'Передняя оптика Mercedes-Benz C217', price: '150.000₽', category: 'front' },
  { id: 5, title: 'Передняя оптика Mercedes-Benz W204', price: '55.000₽', category: 'front' },
  { id: 6, title: 'Передняя оптика Mercedes-Benz V167', price: '189.000₽', category: 'front' },
  {
    id: 7,
    title: 'Поворотники ChargeSpeed Subaru WRX/Forester/Levorg',
    price: '17.500₽',
    priceValue: 17500,
    category: 'front',
    image: '',
    description: '',
    features: {},
  },
  { id: 8, title: 'Передняя оптика Mercedes-Benz S212', price: '67.000₽', category: 'front' },
  { id: 9, title: 'Задние фонари BMW 5-Series F10 (Рест)', price: '25.000₽', category: 'rear' },
  { id: 10, title: 'Передняя оптика Mercedes-Benz W222', price: '125.000₽', category: 'front' },
  { id: 11, title: 'Противотуманные фары универсальные', price: '5500₽', category: 'fog' },
  { id: 12, title: 'Задние фонари Subaru XV', price: '18.500₽', category: 'rear' },
  { id: 13, title: 'Передняя оптика Lada Priora 2', price: '25.000₽', category: 'front' },
  { id: 14, title: 'Передняя оптика Renaul Duster (Рест)', price: '36.000₽', category: 'front' },
  { id: 15, title: 'Задние фонари Mercedes-Benz W140', price: '15.000₽', category: 'rear' },
  { id: 16, title: 'Передняя оптика Ford Focus 3', price: '45.000₽', category: 'front' },
]; 